// ===== HEBREW READING APP - DATA =====
// Complete curriculum for 1st-2nd grade Hebrew reading

const HEBREW_DATA = {
    // ===== LEVEL 1: Letters (אותיות) =====
    letters: [
        { letter: 'א', name: 'אָלֶף', sound: 'silent / glottal stop', hint: 'אות שקטה - היא לא משמיעה צליל בעצמה' },
        { letter: 'בּ', name: 'בֵּית', sound: 'B', hint: 'כמו ב-בַּלוֹן 🎈' },
        { letter: 'ג', name: 'גִּימֶל', sound: 'G', hint: 'כמו ב-גִּירָפָה 🦒' },
        { letter: 'ד', name: 'דָּלֶת', sound: 'D', hint: 'כמו ב-דָּג 🐟' },
        { letter: 'ה', name: 'הֵא', sound: 'H', hint: 'כמו ב-הַר ⛰️' },
        { letter: 'ו', name: 'וָו', sound: 'V', hint: 'כמו ב-וֶרֶד 🌹' },
        { letter: 'ז', name: 'זַיִן', sound: 'Z', hint: 'כמו ב-זֵאב 🐺' },
        { letter: 'ח', name: 'חֵית', sound: 'Ch', hint: 'כמו ב-חָתוּל 🐱' },
        { letter: 'ט', name: 'טֵית', sound: 'T', hint: 'כמו ב-טִיל 🚀' },
        { letter: 'י', name: 'יוֹד', sound: 'Y', hint: 'כמו ב-יַד ✋' },
        { letter: 'כּ', name: 'כַּף', sound: 'K', hint: 'כמו ב-כֶּלֶב 🐕' },
        { letter: 'ל', name: 'לָמֶד', sound: 'L', hint: 'כמו ב-לֵב ❤️' },
        { letter: 'מ', name: 'מֵם', sound: 'M', hint: 'כמו ב-מַיִם 💧' },
        { letter: 'נ', name: 'נוּן', sound: 'N', hint: 'כמו ב-נֵר 🕯️' },
        { letter: 'ס', name: 'סָמֶך', sound: 'S', hint: 'כמו ב-סוּס 🐴' },
        { letter: 'ע', name: 'עַיִן', sound: 'silent / guttural', hint: 'כמו ב-עַיִן 👁️' },
        { letter: 'פּ', name: 'פֵּא', sound: 'P', hint: 'כמו ב-פִּיל 🐘' },
        { letter: 'צ', name: 'צָדִי', sound: 'Ts', hint: 'כמו ב-צִפּוֹר 🐦' },
        { letter: 'ק', name: 'קוֹף', sound: 'K', hint: 'כמו ב-קוֹף 🐵' },
        { letter: 'ר', name: 'רֵישׁ', sound: 'R', hint: 'כמו ב-רוֹבּוֹט 🤖' },
        { letter: 'שׁ', name: 'שִׁין', sound: 'Sh', hint: 'כמו ב-שֶׁמֶשׁ ☀️' },
        { letter: 'תּ', name: 'תָּו', sound: 'T', hint: 'כמו ב-תַּפּוּחַ 🍎' },
    ],

    // ===== LEVEL 2: Vowels (ניקוד) =====
    vowels: [
        { vowel: 'ָ', name: 'קָמָץ', sound: 'A (ah)', example: 'בָּ', hint: 'פה פתוח - אָאָאָ', position: 'below' },
        { vowel: 'ַ', name: 'פַּתָח', sound: 'A (ah)', example: 'בַּ', hint: 'גם פה פתוח - אַאַאַ', position: 'below' },
        { vowel: 'ֵ', name: 'צֵרֵי', sound: 'E (eh)', example: 'בֵּ', hint: 'שתי נקודות - אֵאֵאֵ', position: 'below' },
        { vowel: 'ֶ', name: 'סֶגוֹל', sound: 'E (eh)', example: 'בֶּ', hint: 'שלוש נקודות - אֶאֶאֶ', position: 'below' },
        { vowel: 'ִ', name: 'חִירִיק', sound: 'I (ee)', example: 'בִּ', hint: 'נקודה אחת למטה - אִאִאִ', position: 'below' },
        { vowel: 'ֹ', name: 'חוֹלָם', sound: 'O (oh)', example: 'בֹּ', hint: 'נקודה למעלה - אוֹאוֹאוֹ', position: 'above' },
        { vowel: 'וֹ', name: 'חוֹלָם מָלֵא', sound: 'O (oh)', example: 'בּוֹ', hint: 'וָו עם נקודה - אוֹאוֹאוֹ', position: 'above' },
        { vowel: 'ֻ', name: 'קֻבּוּץ', sound: 'U (oo)', example: 'בֻּ', hint: 'שלוש נקודות אלכסוניות - אוּאוּאוּ', position: 'below' },
        { vowel: 'וּ', name: 'שׁוּרוּק', sound: 'U (oo)', example: 'בּוּ', hint: 'וָו עם נקודה באמצע - אוּאוּאוּ', position: 'middle' },
        { vowel: 'ְ', name: 'שְׁוָא', sound: 'short / silent', example: 'בְּ', hint: 'שתי נקודות אנכיות - לפעמים שקט', position: 'below' },
    ],

    // ===== LEVEL 3+: Syllable combinations =====
    // Each group combines consonants with a specific vowel
    syllableGroups: [
        {
            id: 'kamatz',
            name: 'הברות עם קָמָץ',
            vowelName: 'קָמָץ',
            vowelSymbol: 'ָ',
            icon: '🔤',
            syllables: [
                { text: 'בָּ', sound: 'BA' },
                { text: 'גָּ', sound: 'GA' },
                { text: 'דָּ', sound: 'DA' },
                { text: 'הָ', sound: 'HA' },
                { text: 'וָ', sound: 'VA' },
                { text: 'זָ', sound: 'ZA' },
                { text: 'חָ', sound: 'CHA' },
                { text: 'טָ', sound: 'TA' },
                { text: 'יָ', sound: 'YA' },
                { text: 'כָּ', sound: 'KA' },
                { text: 'לָ', sound: 'LA' },
                { text: 'מָ', sound: 'MA' },
                { text: 'נָ', sound: 'NA' },
                { text: 'סָ', sound: 'SA' },
                { text: 'פָּ', sound: 'PA' },
                { text: 'צָ', sound: 'TSA' },
                { text: 'קָ', sound: 'KA' },
                { text: 'רָ', sound: 'RA' },
                { text: 'שָׁ', sound: 'SHA' },
                { text: 'תָּ', sound: 'TA' },
            ]
        },
        {
            id: 'patach',
            name: 'הברות עם פַּתָח',
            vowelName: 'פַּתָח',
            vowelSymbol: 'ַ',
            icon: '📝',
            syllables: [
                { text: 'בַּ', sound: 'BA' },
                { text: 'גַּ', sound: 'GA' },
                { text: 'דַּ', sound: 'DA' },
                { text: 'הַ', sound: 'HA' },
                { text: 'וַ', sound: 'VA' },
                { text: 'זַ', sound: 'ZA' },
                { text: 'חַ', sound: 'CHA' },
                { text: 'טַ', sound: 'TA' },
                { text: 'יַ', sound: 'YA' },
                { text: 'כַּ', sound: 'KA' },
                { text: 'לַ', sound: 'LA' },
                { text: 'מַ', sound: 'MA' },
                { text: 'נַ', sound: 'NA' },
                { text: 'סַ', sound: 'SA' },
                { text: 'פַּ', sound: 'PA' },
                { text: 'רַ', sound: 'RA' },
                { text: 'שַׁ', sound: 'SHA' },
                { text: 'תַּ', sound: 'TA' },
            ]
        },
        {
            id: 'tsere',
            name: 'הברות עם צֵרֵי',
            vowelName: 'צֵרֵי',
            vowelSymbol: 'ֵ',
            icon: '✏️',
            syllables: [
                { text: 'בֵּ', sound: 'BE' },
                { text: 'גֵּ', sound: 'GE' },
                { text: 'דֵּ', sound: 'DE' },
                { text: 'הֵ', sound: 'HE' },
                { text: 'וֵ', sound: 'VE' },
                { text: 'זֵ', sound: 'ZE' },
                { text: 'חֵ', sound: 'CHE' },
                { text: 'טֵ', sound: 'TE' },
                { text: 'יֵ', sound: 'YE' },
                { text: 'כֵּ', sound: 'KE' },
                { text: 'לֵ', sound: 'LE' },
                { text: 'מֵ', sound: 'ME' },
                { text: 'נֵ', sound: 'NE' },
                { text: 'סֵ', sound: 'SE' },
                { text: 'פֵּ', sound: 'PE' },
                { text: 'רֵ', sound: 'RE' },
                { text: 'שֵׁ', sound: 'SHE' },
                { text: 'תֵּ', sound: 'TE' },
            ]
        },
        {
            id: 'chirik',
            name: 'הברות עם חִירִיק',
            vowelName: 'חִירִיק',
            vowelSymbol: 'ִ',
            icon: '📖',
            syllables: [
                { text: 'בִּ', sound: 'BI' },
                { text: 'גִּ', sound: 'GI' },
                { text: 'דִּ', sound: 'DI' },
                { text: 'הִ', sound: 'HI' },
                { text: 'וִ', sound: 'VI' },
                { text: 'זִ', sound: 'ZI' },
                { text: 'חִ', sound: 'CHI' },
                { text: 'טִ', sound: 'TI' },
                { text: 'יִ', sound: 'YI' },
                { text: 'כִּ', sound: 'KI' },
                { text: 'לִ', sound: 'LI' },
                { text: 'מִ', sound: 'MI' },
                { text: 'נִ', sound: 'NI' },
                { text: 'סִ', sound: 'SI' },
                { text: 'פִּ', sound: 'PI' },
                { text: 'רִ', sound: 'RI' },
                { text: 'שִׁ', sound: 'SHI' },
                { text: 'תִּ', sound: 'TI' },
            ]
        },
        {
            id: 'cholam',
            name: 'הברות עם חוֹלָם',
            vowelName: 'חוֹלָם',
            vowelSymbol: 'וֹ',
            icon: '🔵',
            syllables: [
                { text: 'בּוֹ', sound: 'BO' },
                { text: 'גּוֹ', sound: 'GO' },
                { text: 'דּוֹ', sound: 'DO' },
                { text: 'הוֹ', sound: 'HO' },
                { text: 'זוֹ', sound: 'ZO' },
                { text: 'חוֹ', sound: 'CHO' },
                { text: 'טוֹ', sound: 'TO' },
                { text: 'יוֹ', sound: 'YO' },
                { text: 'כּוֹ', sound: 'KO' },
                { text: 'לוֹ', sound: 'LO' },
                { text: 'מוֹ', sound: 'MO' },
                { text: 'נוֹ', sound: 'NO' },
                { text: 'סוֹ', sound: 'SO' },
                { text: 'פּוֹ', sound: 'PO' },
                { text: 'רוֹ', sound: 'RO' },
                { text: 'שׁוֹ', sound: 'SHO' },
                { text: 'תּוֹ', sound: 'TO' },
            ]
        },
        {
            id: 'shuruk',
            name: 'הברות עם שׁוּרוּק',
            vowelName: 'שׁוּרוּק',
            vowelSymbol: 'וּ',
            icon: '🟣',
            syllables: [
                { text: 'בּוּ', sound: 'BU' },
                { text: 'גּוּ', sound: 'GU' },
                { text: 'דּוּ', sound: 'DU' },
                { text: 'הוּ', sound: 'HU' },
                { text: 'זוּ', sound: 'ZU' },
                { text: 'חוּ', sound: 'CHU' },
                { text: 'טוּ', sound: 'TU' },
                { text: 'יוּ', sound: 'YU' },
                { text: 'כּוּ', sound: 'KU' },
                { text: 'לוּ', sound: 'LU' },
                { text: 'מוּ', sound: 'MU' },
                { text: 'נוּ', sound: 'NU' },
                { text: 'סוּ', sound: 'SU' },
                { text: 'פּוּ', sound: 'PU' },
                { text: 'רוּ', sound: 'RU' },
                { text: 'שׁוּ', sound: 'SHU' },
                { text: 'תּוּ', sound: 'TU' },
            ]
        },
    ],

    // ===== WORD LEVELS =====
    wordGroups: [
        {
            id: 'words-2letter',
            name: 'מילים קצרות',
            description: 'מילים בנות שתי אותיות',
            icon: '🌱',
            words: [
                { word: 'אָב', meaning: 'אבא', image: '👨', syllables: ['אָב'] },
                { word: 'אֵם', meaning: 'אמא', image: '👩', syllables: ['אֵם'] },
                { word: 'יָד', meaning: 'יד', image: '✋', syllables: ['יָד'] },
                { word: 'גָן', meaning: 'גן', image: '🌳', syllables: ['גָן'] },
                { word: 'דָג', meaning: 'דג', image: '🐟', syllables: ['דָג'] },
                { word: 'הַר', meaning: 'הר', image: '⛰️', syllables: ['הַר'] },
                { word: 'זֵאב', meaning: 'זאב', image: '🐺', syllables: ['זֵאב'] },
                { word: 'חָם', meaning: 'חם', image: '🌡️', syllables: ['חָם'] },
                { word: 'טוֹב', meaning: 'טוב', image: '👍', syllables: ['טוֹב'] },
                { word: 'כַּד', meaning: 'כד', image: '🏺', syllables: ['כַּד'] },
                { word: 'לֵב', meaning: 'לב', image: '❤️', syllables: ['לֵב'] },
                { word: 'נֵר', meaning: 'נר', image: '🕯️', syllables: ['נֵר'] },
                { word: 'סוּס', meaning: 'סוס', image: '🐴', syllables: ['סוּס'] },
                { word: 'פַּר', meaning: 'פר', image: '🐂', syllables: ['פַּר'] },
                { word: 'קוֹל', meaning: 'קול', image: '🔊', syllables: ['קוֹל'] },
            ]
        },
        {
            id: 'words-simple',
            name: 'מילים פשוטות',
            description: 'מילים בנות שלוש אותיות',
            icon: '🌿',
            words: [
                { word: 'בַּיִת', meaning: 'בית', image: '🏠', syllables: ['בַּ', 'יִת'] },
                { word: 'סֵפֶר', meaning: 'ספר', image: '📖', syllables: ['סֵ', 'פֶר'] },
                { word: 'שֶׁמֶשׁ', meaning: 'שמש', image: '☀️', syllables: ['שֶׁ', 'מֶשׁ'] },
                { word: 'יֶלֶד', meaning: 'ילד', image: '👦', syllables: ['יֶ', 'לֶד'] },
                { word: 'יַלְדָּה', meaning: 'ילדה', image: '👧', syllables: ['יַלְ', 'דָּה'] },
                { word: 'כֶּלֶב', meaning: 'כלב', image: '🐕', syllables: ['כֶּ', 'לֶב'] },
                { word: 'חָתוּל', meaning: 'חתול', image: '🐱', syllables: ['חָ', 'תוּל'] },
                { word: 'פֶּרַח', meaning: 'פרח', image: '🌸', syllables: ['פֶּ', 'רַח'] },
                { word: 'גֶּשֶׁם', meaning: 'גשם', image: '🌧️', syllables: ['גֶּ', 'שֶׁם'] },
                { word: 'לֶחֶם', meaning: 'לחם', image: '🍞', syllables: ['לֶ', 'חֶם'] },
                { word: 'מַיִם', meaning: 'מים', image: '💧', syllables: ['מַ', 'יִם'] },
                { word: 'דֶּלֶת', meaning: 'דלת', image: '🚪', syllables: ['דֶּ', 'לֶת'] },
                { word: 'עוּגָה', meaning: 'עוגה', image: '🎂', syllables: ['עוּ', 'גָה'] },
                { word: 'תַּפּוּחַ', meaning: 'תפוח', image: '🍎', syllables: ['תַּ', 'פּוּחַ'] },
                { word: 'בָּנָנָה', meaning: 'בננה', image: '🍌', syllables: ['בָּ', 'נָ', 'נָה'] },
            ]
        },
        {
            id: 'words-animals',
            name: 'חיות',
            description: 'שמות של חיות',
            icon: '🦁',
            words: [
                { word: 'אַרְיֵה', meaning: 'אריה', image: '🦁', syllables: ['אַרְ', 'יֵה'] },
                { word: 'פִּיל', meaning: 'פיל', image: '🐘', syllables: ['פִּיל'] },
                { word: 'קוֹף', meaning: 'קוף', image: '🐵', syllables: ['קוֹף'] },
                { word: 'צִפּוֹר', meaning: 'ציפור', image: '🐦', syllables: ['צִ', 'פּוֹר'] },
                { word: 'דֻּבּ', meaning: 'דוב', image: '🐻', syllables: ['דֻּבּ'] },
                { word: 'נָחָשׁ', meaning: 'נחש', image: '🐍', syllables: ['נָ', 'חָשׁ'] },
                { word: 'צָב', meaning: 'צב', image: '🐢', syllables: ['צָב'] },
                { word: 'פַּרְפַּר', meaning: 'פרפר', image: '🦋', syllables: ['פַּרְ', 'פַּר'] },
                { word: 'דְּבוֹרָה', meaning: 'דבורה', image: '🐝', syllables: ['דְּ', 'בוֹ', 'רָה'] },
                { word: 'תַּרְנְגוֹל', meaning: 'תרנגול', image: '🐓', syllables: ['תַּרְ', 'נְ', 'גוֹל'] },
                { word: 'אַרְנָב', meaning: 'ארנב', image: '🐰', syllables: ['אַרְ', 'נָב'] },
                { word: 'גִּירָפָה', meaning: 'ג׳ירפה', image: '🦒', syllables: ['גִּי', 'רָ', 'פָה'] },
            ]
        },
        {
            id: 'words-food',
            name: 'אוכל',
            description: 'שמות של מאכלים',
            icon: '🍕',
            words: [
                { word: 'חָלָב', meaning: 'חלב', image: '🥛', syllables: ['חָ', 'לָב'] },
                { word: 'גְּלִידָה', meaning: 'גלידה', image: '🍦', syllables: ['גְּ', 'לִי', 'דָה'] },
                { word: 'שׁוֹקוֹלָד', meaning: 'שוקולד', image: '🍫', syllables: ['שׁוֹ', 'קוֹ', 'לָד'] },
                { word: 'פִּיצָה', meaning: 'פיצה', image: '🍕', syllables: ['פִּי', 'צָה'] },
                { word: 'עוּגִיָּה', meaning: 'עוגייה', image: '🍪', syllables: ['עוּ', 'גִי', 'יָה'] },
                { word: 'תּוּת', meaning: 'תות', image: '🍓', syllables: ['תּוּת'] },
                { word: 'אֲבַטִּיחַ', meaning: 'אבטיח', image: '🍉', syllables: ['אֲ', 'בַ', 'טִּיחַ'] },
                { word: 'עִנְבִים', meaning: 'ענבים', image: '🍇', syllables: ['עִנְ', 'בִים'] },
                { word: 'גֶּזֶר', meaning: 'גזר', image: '🥕', syllables: ['גֶּ', 'זֶר'] },
                { word: 'בֵּיצָה', meaning: 'ביצה', image: '🥚', syllables: ['בֵּי', 'צָה'] },
            ]
        },
        {
            id: 'words-nature',
            name: 'טבע',
            description: 'מילים מהטבע',
            icon: '🌳',
            words: [
                { word: 'עֵץ', meaning: 'עץ', image: '🌳', syllables: ['עֵץ'] },
                { word: 'פֶּרַח', meaning: 'פרח', image: '🌸', syllables: ['פֶּ', 'רַח'] },
                { word: 'שָׁמַיִם', meaning: 'שמיים', image: '🌤️', syllables: ['שָׁ', 'מַ', 'יִם'] },
                { word: 'כּוֹכָב', meaning: 'כוכב', image: '⭐', syllables: ['כּוֹ', 'כָב'] },
                { word: 'יָרֵחַ', meaning: 'ירח', image: '🌙', syllables: ['יָ', 'רֵ', 'חַ'] },
                { word: 'עָנָן', meaning: 'ענן', image: '☁️', syllables: ['עָ', 'נָן'] },
                { word: 'קֶשֶׁת', meaning: 'קשת', image: '🌈', syllables: ['קֶ', 'שֶׁת'] },
                { word: 'יָם', meaning: 'ים', image: '🌊', syllables: ['יָם'] },
                { word: 'חוֹל', meaning: 'חול', image: '🏖️', syllables: ['חוֹל'] },
                { word: 'אֶבֶן', meaning: 'אבן', image: '🪨', syllables: ['אֶ', 'בֶן'] },
            ]
        },
        {
            id: 'sentences-simple',
            name: 'משפטים קצרים',
            description: 'קוראים משפטים!',
            icon: '📝',
            words: [
                { word: 'אָבָא בָּא', meaning: 'אבא בא', image: '👨', syllables: ['אָ', 'בָא', 'בָּא'] },
                { word: 'אִמָּא פֹּה', meaning: 'אמא פה', image: '👩', syllables: ['אִ', 'מָּא', 'פֹּה'] },
                { word: 'הַיֶּלֶד רָץ', meaning: 'הילד רץ', image: '🏃', syllables: ['הַ', 'יֶּ', 'לֶד', 'רָץ'] },
                { word: 'הַכֶּלֶב גָּדוֹל', meaning: 'הכלב גדול', image: '🐕', syllables: ['הַ', 'כֶּ', 'לֶב', 'גָּ', 'דוֹל'] },
                { word: 'הַחָתוּל יָשֵׁן', meaning: 'החתול ישן', image: '😺', syllables: ['הַ', 'חָ', 'תוּל', 'יָ', 'שֵׁן'] },
                { word: 'אֲנִי אוֹהֵב', meaning: 'אני אוהב', image: '❤️', syllables: ['אֲ', 'נִי', 'אוֹ', 'הֵב'] },
                { word: 'הַשֶּׁמֶשׁ זוֹרַחַת', meaning: 'השמש זורחת', image: '☀️', syllables: ['הַ', 'שֶּׁ', 'מֶשׁ', 'זוֹ', 'רַ', 'חַת'] },
                { word: 'יֵשׁ לִי סֵפֶר', meaning: 'יש לי ספר', image: '📖', syllables: ['יֵשׁ', 'לִי', 'סֵ', 'פֶר'] },
            ]
        }
    ],

    // ===== LEVEL DEFINITIONS =====
    levels: [
        { id: 'letters-1', type: 'learn-letters', name: 'אותיות א-ה', icon: '🔤', dataSlice: [0, 5], color: '#667eea' },
        { id: 'letters-2', type: 'learn-letters', name: 'אותיות ו-י', icon: '🔤', dataSlice: [5, 10], color: '#7c3aed' },
        { id: 'letters-3', type: 'learn-letters', name: 'אותיות כ-ס', icon: '🔤', dataSlice: [10, 15], color: '#2563eb' },
        { id: 'letters-4', type: 'learn-letters', name: 'אותיות ע-ת', icon: '🔤', dataSlice: [15, 22], color: '#0891b2' },
        { id: 'vowels', type: 'learn-vowels', name: 'ניקוד', icon: '🎵', dataSlice: [0, 10], color: '#dc2626' },
        { id: 'syl-kamatz', type: 'learn-syllables', name: 'הברות קָמָץ', icon: '🔤', groupIndex: 0, color: '#ea580c' },
        { id: 'syl-patach', type: 'learn-syllables', name: 'הברות פַּתָח', icon: '📝', groupIndex: 1, color: '#d97706' },
        { id: 'syl-tsere', type: 'learn-syllables', name: 'הברות צֵרֵי', icon: '✏️', groupIndex: 2, color: '#65a30d' },
        { id: 'syl-chirik', type: 'learn-syllables', name: 'הברות חִירִיק', icon: '📖', groupIndex: 3, color: '#0d9488' },
        { id: 'syl-cholam', type: 'learn-syllables', name: 'הברות חוֹלָם', icon: '🔵', groupIndex: 4, color: '#2563eb' },
        { id: 'syl-shuruk', type: 'learn-syllables', name: 'הברות שׁוּרוּק', icon: '🟣', groupIndex: 5, color: '#7c3aed' },
        { id: 'words-2letter', type: 'learn-words', name: 'מילים קצרות', icon: '🌱', groupIndex: 0, color: '#16a34a' },
        { id: 'words-simple', type: 'learn-words', name: 'מילים פשוטות', icon: '🌿', groupIndex: 1, color: '#059669' },
        { id: 'words-animals', type: 'learn-words', name: 'חיות', icon: '🦁', groupIndex: 2, color: '#ca8a04' },
        { id: 'words-food', type: 'learn-words', name: 'אוכל', icon: '🍕', groupIndex: 3, color: '#e11d48' },
        { id: 'words-nature', type: 'learn-words', name: 'טבע', icon: '🌳', groupIndex: 4, color: '#15803d' },
        { id: 'sentences', type: 'learn-words', name: 'משפטים', icon: '📝', groupIndex: 5, color: '#7e22ce' },
    ]
};
